"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {API} from "@/lib/api";
import {localISODate} from "@/lib/datetime";
import ProjectionChart from "@/components/ProjectionChart";
import SeasonPlanner from "@/components/SeasonPlanner";

type Objective={id:number;name:string;event_date:string;sport:string;priority:string;distance_m?:number;elevation_m?:number};
type Block={id:number;name:string;block_type:string;start_date:string;end_date:string;targets:any;objective_id?:number};
const iso=localISODate;
export default function SeasonClient(){
 const [objectives,setObjectives]=useState<Objective[]>([]);const [blocks,setBlocks]=useState<Block[]>([]);const [projection,setProjection]=useState<any>({series:[],warnings:[]});const [error,setError]=useState("");
 const today=new Date();const yearEnd=new Date(today);yearEnd.setFullYear(today.getFullYear()+1);
 const [obj,setObj]=useState({name:"Target race",event_date:iso(yearEnd),sport:"running",priority:"A",distanceKm:"",elevationM:""});
 const [block,setBlock]=useState({name:"Base",block_type:"base",start_date:iso(today),end_date:iso(new Date(today.getTime()+42*86400000)),targetLoad:"450",objective_id:""});
 const load=useCallback(async()=>{try{const [o,b,p]=await Promise.all([fetch(`${API}/objectives`).then(r=>r.json()),fetch(`${API}/training-blocks`).then(r=>r.json()),fetch(`${API}/analytics/projection?start=${iso(new Date(today.getTime()-30*86400000))}&end=${iso(yearEnd)}`).then(r=>r.json())]);setObjectives(o);setBlocks(b);setProjection(p)}catch(e:any){setError(e.message)}},[]);
 useEffect(()=>{load()},[load]);
 async function createObjective(e:React.FormEvent){e.preventDefault();const r=await fetch(`${API}/objectives`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:obj.name,event_date:obj.event_date,sport:obj.sport,priority:obj.priority,distance_m:obj.distanceKm?Number(obj.distanceKm)*1000:null,elevation_m:obj.elevationM?Number(obj.elevationM):null})});if(!r.ok){setError(await r.text());return}await load()}
 async function createBlock(e:React.FormEvent){e.preventDefault();const r=await fetch(`${API}/training-blocks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:block.name,block_type:block.block_type,start_date:block.start_date,end_date:block.end_date,objective_id:block.objective_id?Number(block.objective_id):null,targets:{weekly_load:Number(block.targetLoad)}})});if(!r.ok){setError(await r.text());return}await load()}
 const range=useMemo(()=>{const dates=[...blocks.flatMap(b=>[new Date(b.start_date).getTime(),new Date(b.end_date).getTime()]),...objectives.map(o=>new Date(o.event_date).getTime()),Date.now()];return {min:Math.min(...dates),max:Math.max(...dates,Date.now()+90*86400000)}},[blocks,objectives]);
 const pct=(d:string)=>Math.max(0,Math.min(100,(new Date(d).getTime()-range.min)/(range.max-range.min)*100));
 return <><h1>Season</h1><p className="muted">Objectives, training phases and the projected fitness trajectory driven by your calendar.</p>{error&&<div className="card section errorText">{error}</div>}
 <div className="card section"><div className="row spread"><div><h2>Season timeline</h2><p className="muted">Blocks provide the deterministic structure the AI planner will operate inside.</p></div><div className="muted">{new Date(range.min).toLocaleDateString()} - {new Date(range.max).toLocaleDateString()}</div></div><div className="timeline">
  {blocks.map(b=><div className={`timelineBlock ${b.block_type}`} key={b.id} style={{left:`${pct(b.start_date)}%`,width:`${Math.max(2,pct(b.end_date)-pct(b.start_date))}%`}} title={`${b.start_date} - ${b.end_date}`}><b>{b.name}</b><small>{b.block_type}</small></div>)}
  {objectives.map(o=><div className="timelineObjective" key={o.id} style={{left:`${pct(o.event_date)}%`}} title={o.event_date}><span>{o.priority}</span><b>{o.name}</b></div>)}
 </div></div>
 <div className="card section"><h2>Actual and projected fitness</h2><p className="muted">Future sessions use planned load; historical days use measured activity load.</p><ProjectionChart data={projection.series||[]}/>{projection.warnings?.length>0&&<div className="warningStack">{projection.warnings.slice(0,5).map((w:any,i:number)=><div className={`warning ${w.severity}`} key={i}>{w.message}</div>)}</div>}</div>
 <div className="twoCol section"><form className="card" onSubmit={createObjective}><h2>Add objective</h2><div className="formGrid"><label className="span2">Name<input className="input" value={obj.name} onChange={e=>setObj({...obj,name:e.target.value})}/></label><label>Date<input className="input" type="date" value={obj.event_date} onChange={e=>setObj({...obj,event_date:e.target.value})}/></label><label>Priority<select className="input" value={obj.priority} onChange={e=>setObj({...obj,priority:e.target.value})}><option>A</option><option>B</option><option>C</option></select></label><label>Sport<select className="input" value={obj.sport} onChange={e=>setObj({...obj,sport:e.target.value})}><option>running</option><option>trail_running</option><option>cycling</option><option>mountaineering</option></select></label><label>Distance km<input className="input" type="number" value={obj.distanceKm} onChange={e=>setObj({...obj,distanceKm:e.target.value})}/></label><label>Elevation m<input className="input" type="number" value={obj.elevationM} onChange={e=>setObj({...obj,elevationM:e.target.value})}/></label></div><button className="button section">Create objective</button></form>
 <form className="card" onSubmit={createBlock}><h2>Add training block</h2><div className="formGrid"><label>Name<input className="input" value={block.name} onChange={e=>setBlock({...block,name:e.target.value})}/></label><label>Type<select className="input" value={block.block_type} onChange={e=>setBlock({...block,block_type:e.target.value})}>{["foundation","base","build","specific","peak","taper","recovery"].map(x=><option key={x}>{x}</option>)}</select></label><label>Start<input className="input" type="date" value={block.start_date} onChange={e=>setBlock({...block,start_date:e.target.value})}/></label><label>End<input className="input" type="date" value={block.end_date} onChange={e=>setBlock({...block,end_date:e.target.value})}/></label><label>Target weekly load<input className="input" type="number" value={block.targetLoad} onChange={e=>setBlock({...block,targetLoad:e.target.value})}/></label><label>Objective<select className="input" value={block.objective_id} onChange={e=>setBlock({...block,objective_id:e.target.value})}><option value="">None</option>{objectives.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></div><button className="button section">Create block</button></form></div>
 <div className="twoCol section"><div className="card"><h2>Objectives</h2>{objectives.length===0?<p className="muted">No objectives yet.</p>:objectives.map(o=><div className="listRow" key={o.id}><div><b>{o.priority} · {o.name}</b><div className="muted">{o.event_date} · {o.sport}</div></div><div>{o.distance_m?`${Math.round(o.distance_m/1000)} km`:""} {o.elevation_m?`· ${Math.round(o.elevation_m)}m+`:""}</div></div>)}</div><div className="card"><h2>Training blocks</h2>{blocks.length===0?<p className="muted">No blocks yet.</p>:blocks.map(b=><div className="listRow" key={b.id}><div><b>{b.name}</b><div className="muted">{b.start_date} - {b.end_date}</div></div><span className="badge">{b.block_type}</span></div>)}</div></div>
 </>
}
